name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Display metrics
      - name: Metrics plugin
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: "CSS, HTML"
          plugin_lines: yes
      
      # Display latest starred repositories
      - name: Stars plugin
        uses: lowlighter/metrics@master
        with:
          filename: github-metrics-plugin-stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 4
          plugins_errors_fatal: yes
          use_prebuilt_image: master
